---
linters:
    flake8:
        python: 3
        max-line-length: 120
    pep8:
      max-line-length: 120
    eslint:
    csslint:

files:
    ignore:
        - 'food2/food2/*'
        - './Pipfile'
        - './Pipfile.lock'
        - './food2/manage.py'
        - './food2/locale/*'
        - 'food2/app/static/app/flat-ui/*'
        - 'food2/app/static/app/bootstrap4/*'
