SECRETS_ALLOWED_HOSTS = ['*']
SECRETS_DB_NAME = 'food'
SECRETS_DB_USER = 'user'
SECRETS_DB_PASS = 'pass'
SECRETS_DB_HOST = 'localhost'
SECRETS_DB_PORT = '3306'
SECRETS_DEBUG = False
SECRETS_STATIC_URL = '/static/'
